
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework için Microsoft (R) Build Engine sürüm 17.2.1+52cd2da31
      Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
      
      Oluşturma başlatıldı: 23.11.2023 20:44:29.
      1 düğümünde "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" projesi (varsayılan hedefler).
      PrepareForBuild:
        "Debug\\" dizini oluşturuluyor.
        "Debug\\CompilerIdC.tlog\\" dizini oluşturuluyor.
      InitializeBuildStatus:
        "AlwaysCreate" belirtildiği için "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" oluşturuluyor.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" dosyası siliniyor.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate" öğesine erişiliyor.
      "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
      
      Oluşturma başarılı oldu.
          0 Uyarı
          0 Hata
      
      Geçen Süre 00:00:01.60
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework için Microsoft (R) Build Engine sürüm 17.2.1+52cd2da31
      Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
      
      Oluşturma başlatıldı: 23.11.2023 20:44:31.
      1 düğümünde "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" projesi (varsayılan hedefler).
      PrepareForBuild:
        "Debug\\" dizini oluşturuluyor.
        "Debug\\CompilerIdCXX.tlog\\" dizini oluşturuluyor.
      InitializeBuildStatus:
        "AlwaysCreate" belirtildiği için "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" oluşturuluyor.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" dosyası siliniyor.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" öğesine erişiliyor.
      "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
      
      Oluşturma başarılı oldu.
          0 Uyarı
          0 Hata
      
      Geçen Süre 00:00:01.34
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-a7zu91"
      binary: "C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-a7zu91"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-a7zu91
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_c4f15.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && .NET Framework için Microsoft (R) Build Engine sürüm 17.2.1+52cd2da31
        Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
        
        Oluşturma başlatıldı: 23.11.2023 20:44:33.
        1 düğümünde "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-a7zu91\\cmTC_c4f15.vcxproj" projesi (varsayılan hedefler).
        PrepareForBuild:
          "cmTC_c4f15.dir\\Debug\\" dizini oluşturuluyor.
          "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-a7zu91\\Debug\\" dizini oluşturuluyor.
          "cmTC_c4f15.dir\\Debug\\cmTC_c4f15.tlog\\" dizini oluşturuluyor.
        InitializeBuildStatus:
          "AlwaysCreate" belirtildiği için "cmTC_c4f15.dir\\Debug\\cmTC_c4f15.tlog\\unsuccessfulbuild" oluşturuluyor.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c4f15.dir\\Debug\\\\" /Fd"cmTC_c4f15.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31328 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c4f15.dir\\Debug\\\\" /Fd"cmTC_c4f15.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-a7zu91\\Debug\\cmTC_c4f15.exe" /INCREMENTAL /ILK:"cmTC_c4f15.dir\\Debug\\cmTC_c4f15.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-a7zu91/Debug/cmTC_c4f15.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-a7zu91/Debug/cmTC_c4f15.lib" /MACHINE:X64  /machine:x64 cmTC_c4f15.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_c4f15.vcxproj -> C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-a7zu91\\Debug\\cmTC_c4f15.exe
        FinalizeBuildStatus:
          "cmTC_c4f15.dir\\Debug\\cmTC_c4f15.tlog\\unsuccessfulbuild" dosyası siliniyor.
          "cmTC_c4f15.dir\\Debug\\cmTC_c4f15.tlog\\cmTC_c4f15.lastbuildstate" öğesine erişiliyor.
        "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-a7zu91\\cmTC_c4f15.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
        
        Oluşturma başarılı oldu.
            0 Uyarı
            0 Hata
        
        Geçen Süre 00:00:01.32
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-men4bf"
      binary: "C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-men4bf"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-men4bf
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_24791.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && .NET Framework için Microsoft (R) Build Engine sürüm 17.2.1+52cd2da31
        Telif Hakkı (C) Microsoft Corporation. Tüm hakları saklıdır.
        
        Oluşturma başlatıldı: 23.11.2023 20:44:35.
        1 düğümünde "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-men4bf\\cmTC_24791.vcxproj" projesi (varsayılan hedefler).
        PrepareForBuild:
          "cmTC_24791.dir\\Debug\\" dizini oluşturuluyor.
          "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-men4bf\\Debug\\" dizini oluşturuluyor.
          "cmTC_24791.dir\\Debug\\cmTC_24791.tlog\\" dizini oluşturuluyor.
        InitializeBuildStatus:
          "AlwaysCreate" belirtildiği için "cmTC_24791.dir\\Debug\\cmTC_24791.tlog\\unsuccessfulbuild" oluşturuluyor.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_24791.dir\\Debug\\\\" /Fd"cmTC_24791.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31328 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_24791.dir\\Debug\\\\" /Fd"cmTC_24791.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-men4bf\\Debug\\cmTC_24791.exe" /INCREMENTAL /ILK:"cmTC_24791.dir\\Debug\\cmTC_24791.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-men4bf/Debug/cmTC_24791.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/user/Desktop/Dersler/Workspace/Cpp/Deneme/CMakeFiles/CMakeScratch/TryCompile-men4bf/Debug/cmTC_24791.lib" /MACHINE:X64  /machine:x64 cmTC_24791.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_24791.vcxproj -> C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-men4bf\\Debug\\cmTC_24791.exe
        FinalizeBuildStatus:
          "cmTC_24791.dir\\Debug\\cmTC_24791.tlog\\unsuccessfulbuild" dosyası siliniyor.
          "cmTC_24791.dir\\Debug\\cmTC_24791.tlog\\cmTC_24791.lastbuildstate" öğesine erişiliyor.
        "C:\\Users\\user\\Desktop\\Dersler\\Workspace\\Cpp\\Deneme\\CMakeFiles\\CMakeScratch\\TryCompile-men4bf\\cmTC_24791.vcxproj" Projesini Oluşturma İşlemi Tamamlandı (varsayılan hedefler).
        
        Oluşturma başarılı oldu.
            0 Uyarı
            0 Hata
        
        Geçen Süre 00:00:01.34
        
      exitCode: 0
...
